### ISSUE TITLE
Table for deactivated Spirittypes does not exist

### ISSUE THREAD

**Issue by Joklost** [Joklost/P3-Code#5]
![image](https://cloud.githubusercontent.com/assets/9192329/11766897/d4d47ab8-a19a-11e5-9937-c61d7b3053f2.png)

**Comment by MariusLauge** [comment]
Commented the deactivate button, for now.

**Comment by Joklost** [comment]
It did exist, but this method:
![image](https://cloud.githubusercontent.com/assets/9192329/11768511/c7afe888-a1cf-11e5-85a4-857f30b789c4.png)
originally only returned the active ones to the View.
