### ISSUE TITLE
Deactivated SpiritType is still in CreateBatch

### ISSUE THREAD

**Issue by Joklost** [Joklost/P3-Code#6]
![image](https://cloud.githubusercontent.com/assets/9192329/11766901/fd7fb2b6-a19a-11e5-98d6-570f3bea4ad3.png)

**Comment by MariusLauge** [comment]
Commented out the deactivate button, for now.

**Comment by Joklost** [comment]
![image](https://cloud.githubusercontent.com/assets/9192329/11768548/0104b54a-a1d1-11e5-9e7c-3ecb6059dc61.png)
![image](https://cloud.githubusercontent.com/assets/9192329/11768549/0c653b4e-a1d1-11e5-8cec-f57b14673f5e.png)
Was added to fix the problem.
